---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
data:
  host: bW9uZ29kYi5tb25nby1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw=
  port: MjcwMTc=
  username: cm9vdA==
  password: T1FqcG1ZOEZLMg==
  type: bW9uZ29kYg==