apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
      app.kubernetes.io/name: redis-app
  template:
    metadata:
      labels:
        app: redis-app
        app.kubernetes.io/name: redis-app
    spec:
      containers:
      - name: redis-app
        image: ghcr.io/bzhtux/sample_apps-redis:v0.0.6
        volumeMounts:
        - name: services-binddings
          mountPath: "/bindings"
          readOnly: true
        env:
          - name: SERVICE_BINDING_ROOT
            value: "/bindings"
      volumes:
      - name: services-binddings
        projected:
          sources:
          - secret:
              name: redis-app
              items:
                - key: host
                  path: redis/host
                - key: port
                  path: redis/port
                - key: username
                  path: redis/username
                - key: password
                  path: redis/password
                - key: database
                  path: redis/database
                - key: sslenabled
                  path: redis/ssl
                - key: type
                  path: redis/type

