apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: bzhtux/redis-app:v0.0.1
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
                optional: false
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis
                key: port
                optional: false
          - name: REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                name: redis
                key: username
                optional: false
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
                optional: false
          - name: REDIS_DB
            valueFrom:
              secretKeyRef:
                name: redis
                key: database
                optional: false
          - name: REDIS_SSL
            valueFrom:
              secretKeyRef:
                name: redis
                key: sslenabled
                optional: false
